### PR TITLE
AOT friendly: instrumentStore() and _createExtensionOptions()

### LINKED ISSUE #48: StoreDevtoolsModule.instrumentStore not compatible with AOT
```StoreDevtoolsModule.instrumentOnlyWithExtension()```  works with AOT.
```StoreDevtoolsModule.instrumentStore not compatible with AOT```
getting an error of:
```
ERROR in Error encountered resolving symbol values statically. Calling function 'StoreDevtoolsModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in C:/msweb/studiotouch/src/app/app.module.ts, resolving symbol AppModule in C:/msweb/studiotouch/src/app/app.module.ts
```

And we rely on ```instrumentStore``` as we need to provide maxAge, otherwise our dev tools will not work (large data set)

can we please fix it so it works just like ```instrumentOnlyWithExtension```

```
angular-cli: 1.0.0-beta.25.5
node: 6.5.0
os: win32 x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.2.1
@angular/compiler-cli: 2.4.3
@angular/language-service: 2.4.3
```
thanks as always,

Sean

### PR DESCRIPTION
**Pull request by juanlizarazo**
Fixes #48 StoreDevtoolsModule.instrumentStore not compatible with Ahead of time compilation.

No new functionality added. 
No new tests added. 

All specs passing.

```
> nyc node tests.js

Started
........................


24 specs, 0 failures
Finished in 1.127 seconds

---------------|----------|----------|----------|----------|----------------|
File           |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------|----------|----------|----------|----------|----------------|
All files      |    84.45 |    71.79 |    68.57 |    85.62 |                |
 actions.ts    |    85.71 |       50 |    88.89 |    85.71 |          48,49 |
 config.ts     |      100 |      100 |      100 |      100 |                |
 devtools.ts   |    96.83 |      100 |    76.47 |    96.43 |          80,88 |
 extension.ts  |    71.15 |    33.33 |    31.25 |    76.74 |... 5,90,91,103 |
 instrument.ts |       62 |       50 |    58.33 |    59.57 |... 8,63,65,114 |
 reducer.ts    |     90.7 |       86 |      100 |    92.68 |... 217,221,222 |
 utils.ts      |    94.44 |      100 |    85.71 |    92.86 |             21 |
---------------|----------|----------|----------|----------|----------------|
```

### CODE REVIEW

**Comment by juanlizarazo** [comment]
Closing. Needs work.

**Comment by born2net** [comment]
@juanlizarazo tx for the efforts, I am wondering why the did you close the bug as the issue remains no?
tx again,

Sean

**Comment by juanlizarazo** [comment]
That "closing needs work" comment is on the PR. 

This issue is still open.

**Comment by born2net** [comment]
to who's attention can we bring this to push for a fix?
regards

**Pull request closed without merging**
