### PR TITLE
Fixes issue with latest ng4rc5 release

### LINKED ISSUE #56: new Angular 4 >=rc4 breaks the package
See [store#357](https://github.com/ngrx/store/issues/357)

Basically, new Angular 4 >=rc4 breaks the package.

### PR DESCRIPTION
**Pull request by robertohuertasm**
Fixes [store#357](https://github.com/ngrx/store/issues/357), fixes #56

### CODE REVIEW

**Comment by kondi** [comment]
Angular 4 is just around the corner. This fix is so simple, would be really nice to have it merged and released.

**Comment by cport1** [comment]
Yes! Can we get a merge please :)

**Comment by dereklin** [comment]
+1

**Comment by alastair-todd** [comment]
+1

**Comment by maxime1992** [comment]
I think that tomorrow we'll have to decide whether we prefer to use the devtools or the brand new release of Angular v4 :disappointed: ...
(thanks @robertohuertasm for the fix BTW :smile: !)

**Comment by MikeRyan52** [comment]
Published as v3.2.4

**Pull request merged**
